spring.application.name=campusflow

spring.datasource.url=jdbc:mysql://localhost:3306/campus
spring.datasource.username=root
spring.datasource.password=maicol206

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
stripe.secret-key=${STRIPE_SECRET_KEY}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET:whsec_pendiente}
stripe.price-pago-unico=${STRIPE_PRICE_PAGO_UNICO}
stripe.price-plan-individual=${STRIPE_PRICE_PLAN_INDIVIDUAL}
stripe.url-exito=http://localhost:8080/pago-exitoso
stripe.url-cancelado=http://localhost:8080/pago-cancelado