spring.application.name=campusflow
spring.datasource.url=jdbc:mysql://localhost:3306/campus
spring.datasource.username=root
spring.datasource.password=maicol206
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
server.port=${PORT:8080}
stripe.secret-key=${STRIPE_SECRET_KEY}
stripe.webhook-secret=whsec_SycWax0woyZplK29lUEecYnzcj7lsS2l
stripe.price-pago-unico=${STRIPE_PRICE_PAGO_UNICO}
stripe.price-plan-individual=${STRIPE_PRICE_PLAN_INDIVIDUAL}
stripe.url-exito=http://localhost:8080/pago-exitoso
stripe.url-cancelado=http://localhost:8080/pago-cancelado